// ─── Data Definitions for all 32 Mexican States ───────────────

export interface Ley {
    nombre: string;
    url?: string;
    fecha?: string;
}

export interface CategoriaLeyes {
    constitucion: Ley[];
    leyes: Ley[];
    codigos: Ley[];
    reglamentos: Ley[];
    otros: Ley[];
}

export interface Estado {
    slug: string;
    nombre: string;
    nombreCorto: string;
    abreviatura: string;
    region: 'norte' | 'centro' | 'sur' | 'occidente' | 'oriente';
    leyesCount: number;
    ultimaActualizacion?: string;
    leyes: CategoriaLeyes;
}

// ─── Placeholder for states without data yet ──────────────────
const LEYES_PLACEHOLDER: CategoriaLeyes = {
    constitucion: [],
    leyes: [],
    codigos: [],
    reglamentos: [],
    otros: [],
};

// ─── Querétaro: FULL DATA — PDFs hosted on GCS ───────────────
const QRO_BASE = 'https://storage.googleapis.com/iurexia-leyes/Queretaro';

const QUERETARO_LEYES: CategoriaLeyes = {
    constitucion: [
        { nombre: 'Constitución Política del Estado Libre y Soberano de Querétaro', url: `${QRO_BASE}/Leyes/CON-ID-001.pdf` },
    ],
    leyes: [
        { nombre: 'Ley de Adquisiciones, Enajenaciones, Arrendamientos y Contratación de servicios del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-002.pdf` },
        { nombre: 'Ley de Archivos del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-003.pdf` },
        { nombre: 'Ley de Asociaciones Público Privadas para el Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-004.pdf` },
        { nombre: 'Ley de Cambio Climático para el Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-005.pdf` },
        { nombre: 'Ley de Catastro para el Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-006.pdf` },
        { nombre: 'Ley de Coordinación Fiscal, Estatal Intermunicipal del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-007.pdf` },
        { nombre: 'Ley de Derechos Humanos del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-008.pdf` },
        { nombre: 'Ley de Derechos y Cultura de los Pueblos y Comunidades Indígenas del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-009.pdf` },
        { nombre: 'Ley de Desarrollo Pecuario del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-010.pdf` },
        { nombre: 'Ley de Desarrollo Social del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-011.pdf` },
        { nombre: 'Ley de Deuda Pública del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-012.pdf` },
        { nombre: 'Ley de Donación y Trasplante de Órganos, Tejidos y Células Humanas del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-013.pdf` },
        { nombre: 'Ley de Educación del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-014.pdf` },
        { nombre: 'Ley de Entrega Recepción del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-015.pdf` },
        { nombre: 'Ley de Estacionamientos Públicos y Servicios de Recepción y Depósito de Vehículos para el Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-016.pdf` },
        { nombre: 'Ley de Estímulos Civiles del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-017.pdf` },
        { nombre: 'Ley de Expropiación del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-018.pdf` },
        { nombre: 'Ley de Extinción de Dominio del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-019.pdf` },
        { nombre: 'Ley de Firma Electrónica Avanzada para el Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-020.pdf` },
        { nombre: 'Ley de Fiscalización Superior y Rendición de Cuentas del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-021.pdf` },
        { nombre: 'Ley de Fomento a la Actividad Artesanal en el Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-022.pdf` },
        { nombre: 'Ley de Fomento a las Organizaciones de la Sociedad Civil del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-023.pdf` },
        { nombre: 'Ley de Fomento Apícola y Protección del proceso de Polinización en el Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-024.pdf` },
        { nombre: 'Ley de Fundos Legales del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-025.pdf` },
        { nombre: 'Ley de Gobierno Digital del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-026.pdf` },
        { nombre: 'Ley de Hacienda de los Municipios del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-027.pdf` },
        { nombre: 'Ley de Hacienda del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-028.pdf` },
        { nombre: 'Ley de Igualdad Sustantiva entre Mujeres y Hombres del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-029.pdf` },
        { nombre: 'Ley de Instituciones de Asistencia Privada del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-030.pdf` },
        { nombre: 'Ley de Juicio Político del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-031.pdf` },
        { nombre: 'Ley de Justicia Constitucional del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-032.pdf` },
        { nombre: 'Ley de Justicia para Adolescentes del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-033.pdf` },
        { nombre: 'Ley de la Administración Pública Paraestatal del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-034.pdf` },
        { nombre: 'Ley de la Agencia de Movilidad y Modalidades de Transporte Público para el Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-035.pdf` },
        { nombre: 'Ley de la Secretaría de Seguridad Ciudadana del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-036.pdf` },
        { nombre: 'Ley de la Unidad de medida y actualización del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-037.pdf` },
        { nombre: 'Ley de los Derechos de las Personas Adultas Mayores del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-038.pdf` },
        { nombre: 'Ley de los Derechos de las Niñas, Niños y Adolescentes del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-039.pdf` },
        { nombre: 'Ley de los Trabajadores del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-040.pdf` },
        { nombre: 'Ley de Medios de Impugnación en Materia Electoral del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-041.pdf` },
        { nombre: 'Ley de Mejora Regulatoria del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-042.pdf` },
        { nombre: 'Ley de Obra Pública del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-043.pdf` },
        { nombre: 'Ley de Participación Ciudadana del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-044.pdf` },
        { nombre: 'Ley de Planeación del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-045.pdf` },
        { nombre: 'Ley de Procedimiento Contencioso Administrativo del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-046.pdf` },
        { nombre: 'Ley de Procedimientos Administrativos del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-047.pdf` },
        { nombre: 'Ley de Profesiones del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-048.pdf` },
        { nombre: 'Ley de Protección a Víctimas, Ofendidos y Personas que Intervienen en el Procedimiento Penal del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-049.pdf` },
        { nombre: 'Ley de Protección de Datos Personales en Posesión de Sujetos Obligados del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-050.pdf` },
        { nombre: 'Ley de Publicaciones Oficiales del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-051.pdf` },
        { nombre: 'Ley de Respeto Vecinal para el Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-052.pdf` },
        { nombre: 'Ley de Responsabilidad Patrimonial del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-053.pdf` },
        { nombre: 'Ley de Responsabilidades Administrativas del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-054.pdf` },
        { nombre: 'Ley de Salud del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-055.pdf` },
        { nombre: 'Ley de Salud Mental del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-056.pdf` },
        { nombre: 'Ley de Seguridad para el Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-057.pdf` },
        { nombre: 'Ley de Servicios Auxiliares del Transporte Público del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-058.pdf` },
        { nombre: 'Ley de Tránsito para el estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-059.pdf` },
        { nombre: 'Ley de Transparencia y Acceso a la Información Pública del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-060.pdf` },
        { nombre: 'Ley de Turismo del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-061.pdf` },
        { nombre: 'Ley de Valuación Inmobiliaria para el Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-062.pdf` },
        { nombre: 'Ley del Centro de Capacitación, Formación e Investigación para la Seguridad del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-063.pdf` },
        { nombre: 'Ley del Centro de Prevención social del Delito y la Violencia en el Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-064.pdf` },
        { nombre: 'Ley del Deporte del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-065.pdf` },
        { nombre: 'Ley del Escudo, la Bandera y el Himno del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-066.pdf` },
        { nombre: 'Ley del Instituto de la Defensoría Penal Pública del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-067.pdf` },
        { nombre: 'Ley del Instituto Queretano de las Mujeres', url: `${QRO_BASE}/Leyes/LEY-ID-068.pdf` },
        { nombre: 'Ley del Instituto Registral y Catastral del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-069.pdf` },
        { nombre: 'Ley del Notariado del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-070.pdf` },
        { nombre: 'Ley del Sistema de Asistencia Social del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-071.pdf` },
        { nombre: 'Ley del Sistema de Servicio Profesional de Carrera del Poder Legislativo del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-072.pdf` },
        { nombre: 'Ley del Sistema Estatal Anticorrupción de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-073.pdf` },
        { nombre: 'Ley del Sistema Estatal de Protección Civil, Prevención y Mitigación de Desastres para el Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-074.pdf` },
        { nombre: 'Ley del Sistema para el Desarrollo Integral de la Familia del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-075.pdf` },
        { nombre: 'Ley del Voluntariado del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-076.pdf` },
        { nombre: 'Ley Electoral del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-111.pdf` },
        { nombre: 'Ley Estatal de Acceso de las Mujeres a una Vida Libre de Violencia', url: `${QRO_BASE}/Leyes/LEY-ID-077.pdf` },
        { nombre: 'Ley Industrial del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-078.pdf` },
        { nombre: 'Ley para Agilizar los Procedimientos de Entrega-Recepción de Fraccionamientos en el Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-079.pdf` },
        { nombre: 'Ley para el Desarrollo de los Jóvenes en el Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-080.pdf` },
        { nombre: 'Ley para el Fomento de la Investigación Científica, Tecnológica e Innovación del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-081.pdf` },
        { nombre: 'Ley para el Manejo de los Recursos Públicos del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-082.pdf` },
        { nombre: 'Ley para la Atención de las Migraciones en el Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-083.pdf` },
        { nombre: 'Ley para la Cultura y las Artes del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-084.pdf` },
        { nombre: 'Ley para la Inclusión al Desarrollo Social de las Personas con Discapacidad del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-085.pdf` },
        { nombre: 'Ley para la Prevención, Gestión Integral y Economía Circular de los Residuos del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-086.pdf` },
        { nombre: 'Ley para la Promoción, Fomento y Desarrollo de la Industria Cinematográfica y Audiovisual del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-087.pdf` },
        { nombre: 'Ley para la Regularización de Asentamientos Humanos Irregulares, Predios Urbanos, Predios Rústicos, Predios Familiares y Predios Sociales del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-088.pdf` },
        { nombre: 'Ley para Prevenir, Combatir, y Sancionar la Trata de Personas en el Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-089.pdf` },
        { nombre: 'Ley para prevenir, investigar, sancionar y reparar la desaparición de personas en el Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-090.pdf` },
        { nombre: 'Ley para Prevenir y Eliminar toda Forma de Discriminación en el Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-091.pdf` },
        { nombre: 'Ley que aprueba la Incorporación del Estado de Querétaro y sus Municipios a la Coordinación en Materia Federal de Derechos', url: `${QRO_BASE}/Leyes/LEY-ID-092.pdf` },
        { nombre: 'Ley que crea el Centro de Evaluación y Control de Confianza del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-093.pdf` },
        { nombre: 'Ley que Crea el Centro de Información y Análisis para la Seguridad de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-094.pdf` },
        { nombre: 'Ley que Crea el Instituto Queretano del Emprendimiento y la Innovación', url: `${QRO_BASE}/Leyes/LEY-ID-095.pdf` },
        { nombre: 'Ley que crea la Comisión Estatal de Infraestructura de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-096.pdf` },
        { nombre: 'Ley que crea la Comisión Estatal del Sistema Penitenciario de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-097.pdf` },
        { nombre: 'Ley que crea la Comisión para la Evaluación de la Operación del Sistema de Justicia Penal Acusatorio del Estado de Querétaro "Cosmos"', url: `${QRO_BASE}/Leyes/LEY-ID-098.pdf` },
        { nombre: 'Ley que crea la Escuela Normal Superior de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-099.pdf` },
        { nombre: 'Ley que crea la Orquesta de Cámara de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-100.pdf` },
        { nombre: 'Ley que establece el Secreto Profesional Periodístico en el Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-101.pdf` },
        { nombre: 'Ley que establece las bases para la Prevención y la Atención de la Violencia Familiar en el Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-102.pdf` },
        { nombre: 'Ley que fija el Arancel para el Cobro de Honorarios de Abogados en el Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-103.pdf` },
        { nombre: 'Ley que fija el Arancel para el Cobro de Honorarios Profesionales de los Arquitectos en el Estado de Querétaro Arteaga', url: `${QRO_BASE}/Leyes/LEY-ID-104.pdf` },
        { nombre: 'Ley que regula a los agentes y empresas inmobiliarias en el Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-105.pdf` },
        { nombre: 'Ley que regula el Sistema Estatal de Promoción del uso de la Bicicleta', url: `${QRO_BASE}/Leyes/LEY-ID-106.pdf` },
        { nombre: 'Ley que regula la prestación de los servicios de agua potable, alcantarillado y saneamiento del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-107.pdf` },
        { nombre: 'Ley que Regula la Prestación de Servicios para la Atención, Cuidado y Desarrollo Integral Infantil en el Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-108.pdf` },
        { nombre: 'Ley Registral del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-109.pdf` },
        { nombre: 'Ley sobre bebidas alcohólicas del Estado de Querétaro', url: `${QRO_BASE}/Leyes/LEY-ID-110.pdf` },
        { nombre: 'Ley de la Secretaría de las Mujeres', url: `${QRO_BASE}/Leyes/LEY-ID-112.pdf` },
    ],
    codigos: [
        { nombre: 'Código Ambiental del Estado de Querétaro', url: `${QRO_BASE}/Codigos/COD-ID-01.pdf` },
        { nombre: 'Código Civil del Estado de Querétaro', url: `${QRO_BASE}/Codigos/COD-ID-02.pdf` },
        { nombre: 'Código de Ética del Poder Legislativo del Estado de Querétaro', url: `${QRO_BASE}/Codigos/COD-ID-03.pdf` },
        { nombre: 'Código de Procedimientos Civiles del Estado de Querétaro', url: `${QRO_BASE}/Codigos/COD-ID-04.pdf` },
        { nombre: 'Código Fiscal del Estado de Querétaro', url: `${QRO_BASE}/Codigos/COD-ID-05.pdf` },
        { nombre: 'Código Urbano del Estado de Querétaro', url: `${QRO_BASE}/Codigos/COD-ID-06.pdf` },
        { nombre: 'Código Penal para el Estado de Querétaro', url: `${QRO_BASE}/Codigos/COD-ID-07.pdf` },
    ],
    reglamentos: [
        // Reglamentos Municipales del Municipio de Querétaro
        { nombre: 'Código de Conducta de los Servidores Públicos Municipales de Querétaro 2021', url: `${QRO_BASE}/Reglamentos/Codigo-Conducta-Servidores-Publicos-QRO-2021.pdf` },
        { nombre: 'Código Municipal de Querétaro', url: `${QRO_BASE}/Reglamentos/Codigo-Municipal-Queretaro.pdf` },
        { nombre: 'Lineamientos en Materia de Obra Pública del Municipio de Querétaro', url: `${QRO_BASE}/Reglamentos/Lineamientos-Obra-Publica-Municipio-QRO.pdf` },
        { nombre: 'Protocolo para la Implementación de los Puntos de Control de Alcoholimetría para el Municipio de Querétaro', url: `${QRO_BASE}/Reglamentos/Protocolo-Alcoholimetria-Municipio-QRO.pdf` },
        { nombre: 'Reglamento para la Movilidad y el Tránsito del Municipio de Querétaro', url: `${QRO_BASE}/Reglamentos/Reglamento-Movilidad-Transito-Municipio-QRO.pdf` },
        { nombre: 'Reglamento de Justicia Cívica del Municipio de Querétaro (Marzo 2025)', url: `${QRO_BASE}/Reglamentos/Reglamento-Justicia-Civica-Municipio-QRO-2025.pdf` },
    ],
    otros: [
        // Leyes Orgánicas
        { nombre: 'Ley Orgánica de la Agencia de Energía del Estado de Querétaro', url: `${QRO_BASE}/Ley-Org/ORG-ID-01.pdf` },
        { nombre: 'Ley Orgánica de la Escuela Normal del Estado', url: `${QRO_BASE}/Ley-Org/ORG-ID-02.pdf` },
        { nombre: 'Ley Orgánica de la Fiscalía General del Estado de Querétaro', url: `${QRO_BASE}/Ley-Org/ORG-ID-03.pdf` },
        { nombre: 'Ley Orgánica de la Universidad Autónoma de Querétaro', url: `${QRO_BASE}/Ley-Org/ORG-ID-04.pdf` },
        { nombre: 'Ley Orgánica de la Universidad Tecnológica de Querétaro', url: `${QRO_BASE}/Ley-Org/ORG-ID-05.pdf` },
        { nombre: 'Ley Orgánica del Centro de Conciliación Laboral del Estado de Querétaro', url: `${QRO_BASE}/Ley-Org/ORG-ID-06.pdf` },
        { nombre: 'Ley Orgánica del Colegio de Bachilleres del Estado de Querétaro', url: `${QRO_BASE}/Ley-Org/ORG-ID-07.pdf` },
        { nombre: 'Ley Orgánica del Poder Ejecutivo del Estado de Querétaro', url: `${QRO_BASE}/Ley-Org/ORG-ID-08.pdf` },
        { nombre: 'Ley Orgánica del Poder Judicial del Estado de Querétaro', url: `${QRO_BASE}/Ley-Org/ORG-ID-09.pdf` },
        { nombre: 'Ley Orgánica del Poder Legislativo del Estado de Querétaro', url: `${QRO_BASE}/Ley-Org/ORG-ID-10.pdf` },
        { nombre: 'Ley Orgánica del Tribunal de Justicia Administrativa del Estado de Querétaro', url: `${QRO_BASE}/Ley-Org/ORG-ID-11.pdf` },
        { nombre: 'Ley Orgánica del Tribunal Electoral del Estado de Querétaro', url: `${QRO_BASE}/Ley-Org/ORG-ID-12.pdf` },
        { nombre: 'Ley Orgánica Municipal del Estado de Querétaro', url: `${QRO_BASE}/Ley-Org/ORG-ID-13.pdf` },
    ],
};

// ─── CDMX: FULL DATA from data.consejeria.cdmx.gob.mx ───────
const CDMX_BASE = 'https://data.consejeria.cdmx.gob.mx/images/leyes';

const CDMX_LEYES: CategoriaLeyes = {
    constitucion: [
        { nombre: 'Constitución Política de la Ciudad de México', url: `${CDMX_BASE}/estatutos/CONSTITUCION_POLITICA_DE_LA_CDMX_14.4.pdf` },
    ],
    leyes: [
        { nombre: 'Ley Orgánica del Congreso de la Ciudad de México', url: `${CDMX_BASE}/leyes/2025/LEY_ORGANICA_DEL_CONGRESO_DE_LA_CDMX_7.4.pdf` },
        { nombre: 'Ley que Regula el Uso de Tecnología para la Seguridad Ciudadana de la CDMX', url: `${CDMX_BASE}/2025/181225/LEY_QUE_REGULA_EL_USO_DELA_TECNOLOGA_PARA_LA_SEGURIDAD_CIUDADANA_DE_LA_CDMX_2.5.pdf` },
        { nombre: 'Ley de Protección a la Salud de las Personas No Fumadoras de la Ciudad de México', url: `${CDMX_BASE}/2025/2026/LEY_DE_PROTECCION_A_LA_SALUD_DE_LOS_NO_FUMADORES_2.3.pdf` },
        { nombre: 'Ley de Protección y Fomento al Empleo para la Ciudad de México', url: `${CDMX_BASE}/2025/LEY_DE_PROTECCION_Y_FOMENTO_AL_EMPLEO_PARA_LA_CDMX_2.pdf` },
        { nombre: 'Ley de Educación de la Ciudad de México', url: `${CDMX_BASE}/2025/LEY_DE_EDUCACION_DE_LA_CDMX_3.6.pdf` },
        { nombre: 'Ley de Auditoría y Control Interno de la Administración Pública de la Ciudad de México', url: `${CDMX_BASE}/2025/LEY_DE_AUDITORIA_Y_CONTROL_INTERNO_DE_LA_ADMON_PUBLICA_DE_LA_CDMX_3.3.pdf` },
        { nombre: 'Ley Orgánica del Instituto de Planeación Democrática y Prospectiva de la Ciudad de México', url: `${CDMX_BASE}/2025/LEY_%20ORG_DEL_INST_DE_PLANEACION_DEMOCRATICA%20_Y_PROSPECTIVA_DE_LA_CDMX_3.4.pdf` },
        { nombre: 'Ley Ambiental de la Ciudad de México', url: `${CDMX_BASE}/2025/2026/210126/LEY_AMBIENTAL_DE_LA_CDMX_1.2.pdf` },
        { nombre: 'Ley de Protección de Datos Personales en Posesión de Sujetos Obligados del Distrito Federal', url: `${CDMX_BASE}/leyes/LEYDPROTECCIONDEDATOSPERSONALESPARAELDISTRITOFEDERAL.pdf` },
        { nombre: 'Ley de Acceso de las Mujeres a una Vida Libre de Violencia de la Ciudad de México', url: `${CDMX_BASE}/LEY_DE_ACCESO_DE_LAS_MUJERES_A_UNA_VIDA_LIBRE_DE_VIOLENCIA_DE_LA_CDMX_12.4.pdf` },
        { nombre: 'Ley de los Derechos de Niñas, Niños y Adolescentes de la Ciudad de México', url: `${CDMX_BASE}/LEY_DERECHOS_NINAS_NINOS_ADOLESCENTES_CDMX_7.3.pdf` },
        { nombre: 'Ley para el Reconocimiento y la Atención de las Personas LGBTTTI+ de la Ciudad de México', url: `${CDMX_BASE}/LEY_PARA_RECONOCIMIENTO_Y_LA_ATENCION_DE_LAS_PERSONAS_LGBTTTI_DE_LA_CDMX_4.1.pdf` },
        { nombre: 'Ley para la Celebración de Espectáculos Públicos de la Ciudad de México', url: `${CDMX_BASE}/Ley_para_la_Celebracion_de_Espectaculos_Publicos_de_la_CDMX_3.4.pdf` },
        { nombre: 'Ley Orgánica de Alcaldías de la Ciudad de México', url: `${CDMX_BASE}/LEY_ORGANICA_DE_ALCALDIAS_DE_LA_CDMX_6.3.pdf` },
        { nombre: 'Ley de Vivienda para la Ciudad de México', url: `${CDMX_BASE}/LEY_DE_VIVIENDA_PARA_LA_CDMX_4.3.pdf` },
        { nombre: 'Ley de Seguridad Privada para la Ciudad de México', url: `${CDMX_BASE}/LEY_DE_SEGURIDAD_PRIVADA_PARA_EL_DF_2.2.pdf` },
        { nombre: 'Ley de Salud de la Ciudad de México', url: `${CDMX_BASE}/2025/2026/210126/LEY_DE_SALUD_DE_LA_CIUDAD_DE_MEXICO_3.7.pdf` },
        { nombre: 'Ley de Protección y Bienestar de los Animales de la Ciudad de México', url: `${CDMX_BASE}/2025/2026/190126/LEY_DE_PROTECCION_Y_BIENESTAR_DE_LOS_ANIMALES_DE_LA_CDMX_1.1.5.pdf` },
        { nombre: 'Ley de Mejoramiento Barrial y Comunitario de la Ciudad de México', url: `${CDMX_BASE}/LEY_DE_MEJORAMIENTO_BARRIAL_Y_COMUNITARIO_DEL_DF_2.3.pdf` },
        { nombre: 'Ley de Fomento para la Lectura y el Libro de la Ciudad de México', url: `${CDMX_BASE}/LEY_DE_FOMENTO_PARA_LA_LECTURA_Y_EL_LIBRO_DE_LA_CIUDAD_DE_MEXICO_6.6.pdf` },
        { nombre: 'Ley de Entrega Recepción de los Recursos de la Administración Pública de la Ciudad de México', url: `${CDMX_BASE}/LEY_DE_ENTREGA_RECEPCION_DE_LOS_RECURSOS_DE_LA_ADMINISTRACION_PUBLICA_DE_LA_CDMX_2.2.pdf` },
        { nombre: 'Ley de Ingresos de la Ciudad de México para el Ejercicio Fiscal 2025', url: `${CDMX_BASE}/leyes/LEY_DE_INGRESOS_2025.pdf` },
        { nombre: 'Ley de Memoria de la Ciudad de México', url: `${CDMX_BASE}/leyes/LEY_DE_MEMORIA_DE_LA_CDMX.pdf` },
        { nombre: 'Ley del Derecho al Bienestar e Igualdad Social para la Ciudad de México', url: `${CDMX_BASE}/leyes/LEY_DEL_DERECHO_AL_BIENESTAR_.pdf` },
        { nombre: 'Ley de Cultura Cívica de la Ciudad de México', url: `${CDMX_BASE}/2025/2026/190126/LEY_DE_CULTURA_CIVICA_DE_LA_CIUDAD_DE_MEXICO_2.8.pdf` },
        { nombre: 'Ley de Austeridad, Transparencia en Remuneraciones, Prestaciones y Ejercicio de Recursos de la Ciudad de México', url: `${CDMX_BASE}/LEY_DE_AUSTERIDAD_TRANSP_EN_REMUNERACIONES_PREST_Y_EJERCICIO_DE_RECURSOS_CDMX_6.2.pdf` },
        { nombre: 'Ley del Sistema Anticorrupción de la Ciudad de México', url: `${CDMX_BASE}/2025/LEY_DEL_SISTEMA_ANTICORRUPCION_DE_LA_CDMX_4.3.pdf` },
        { nombre: 'Ley del Sistema de Seguridad Ciudadana de la Ciudad de México', url: `${CDMX_BASE}/2025/2026/210126/LEY_DEL_SISTEMA_DE_SEGURIDAD_CIUDADANA_DE_LA_CDMX_8.3.pdf` },
        { nombre: 'Ley de Responsabilidades Administrativas de la Ciudad de México', url: `${CDMX_BASE}/2025/2026/210126/LEY_DE_RESPONSABILIDADES_ADMINISTRATIVAS_DE_LA_CDMX_7.4.pdf` },
        { nombre: 'Ley de Transparencia, Acceso a la Información Pública y Rendición de Cuentas de la Ciudad de México', url: `${CDMX_BASE}/2025/LEY_DE_TRANSPARENCIA_ACCESO_A_LA_INFORMACION_PUBLICA_Y_RENDICION_DE_CUENTAS_DE_LA_CDMX_8.4.pdf` },
        { nombre: 'Ley de Procedimiento Administrativo de la Ciudad de México', url: `${CDMX_BASE}/2025/2026/210126/LEY_DE_PROC_ADMINISTRATIVO_DE_LA_CDMX_6.3.pdf` },
        { nombre: 'Ley Orgánica del Poder Ejecutivo y de la Administración Pública de la Ciudad de México', url: `${CDMX_BASE}/2025/2026/210126/LEY_ORG_DEL_P_EJEC_Y_DE_LA_AP_DE_LA_CDMX_14.3.pdf` },
        { nombre: 'Ley Orgánica del Tribunal de Justicia Administrativa de la Ciudad de México', url: `${CDMX_BASE}/2025/LEY_ORGANICA_DEL_TRIBUNAL_DE_JUSTICIA_ADMIN_CDMX_4.6.pdf` },
        { nombre: 'Ley Orgánica del Poder Judicial de la Ciudad de México', url: `${CDMX_BASE}/2025/LEY_ORGANICA_DEL_PODER_JUDICIAL_DE_LA_CDMX_5.5.pdf` },
        { nombre: 'Ley de Justicia Administrativa de la Ciudad de México', url: `${CDMX_BASE}/2025/LEY_DE_JUSTICIA_ADMINISTRATIVA_DE_LA_CDMX_4.4.pdf` },
        { nombre: 'Ley del Notariado de la Ciudad de México', url: `${CDMX_BASE}/2025/2026/50226/LEY_DEL_NOTARIADO_DE_LA_CDMX_5.5.pdf` },
        { nombre: 'Ley de Planeación del Desarrollo de la Ciudad de México', url: `${CDMX_BASE}/LEY_DE_PLANEACION_DEL_DESARROLLO_DE_LA_CDMX_3.3.pdf` },
        { nombre: 'Ley del Tribunal Superior de Justicia de la Ciudad de México', url: `${CDMX_BASE}/leyes/LEY_DEL_TSJ_DE_LA_CDMX_3.1.pdf` },
        { nombre: 'Ley de Participación Ciudadana de la Ciudad de México', url: `${CDMX_BASE}/2025/2026/210126/LEY_DE_PARTICIPACION_CIUDADANA_DE_LA_CDMX_5.2.pdf` },
        { nombre: 'Ley de Establecimientos Mercantiles de la Ciudad de México', url: `${CDMX_BASE}/2025/2026/LEY_DE_ESTABLECIMIENTOS_MERCANTILES_DE_LA_CDMX_7.5.pdf` },
        { nombre: 'Ley de Desarrollo Urbano del Distrito Federal', url: `${CDMX_BASE}/2025/2026/210126/LEY_DE_DESARROLLO_URBANO_DEL_DF_10.5.pdf` },
        { nombre: 'Ley de Presupuesto y Gasto Eficiente de la Ciudad de México', url: `${CDMX_BASE}/2025/LEY_DE_PRESUPUESTO_Y_GASTO_EFICIENTE_DE_LA_CDMX_7.4.pdf` },
        { nombre: 'Ley del Régimen Patrimonial y del Servicio Público', url: `${CDMX_BASE}/LEY_DEL_REGIMEN_PATRIMONIAL_Y_DEL_SERVICIO_PUBLICO_8.3.pdf` },
        { nombre: 'Ley de Obras Públicas de la Ciudad de México', url: `${CDMX_BASE}/2025/LEY_DE_OBRAS_PUBLICAS_DE_LA_CDMX_3.3.pdf` },
        { nombre: 'Ley de Adquisiciones para el Distrito Federal', url: `${CDMX_BASE}/2025/LEY_DE_ADQUISICIONES_PARA_EL_DF_4.3.pdf` },
        { nombre: 'Ley de Archivos de la Ciudad de México', url: `${CDMX_BASE}/2025/LEY_DE_ARCHIVOS_DE_LA_CDMX_3.2.pdf` },
        { nombre: 'Ley de Derechos de los Pueblos y Barrios Originarios y Comunidades Indígenas Residentes en la Ciudad de México', url: `${CDMX_BASE}/2025/181225/LEY_DE_DERECHOS_DE_LOS_PUEBLOS_Y_BARRIOS_ORIGINARIOS_DE_LA_CDMX_3.4.pdf` },
        { nombre: 'Ley de Propiedad en Condominio de Inmuebles para el Distrito Federal', url: `${CDMX_BASE}/2025/2026/210126/LEY_DE_PROPIEDAD_EN_CONDOMINIO_DE_INMUEBLES_PARA_EL_DF_6.7.pdf` },
        { nombre: 'Ley del Instituto de Verificación Administrativa de la Ciudad de México', url: `${CDMX_BASE}/LEY_DEL_INST_DE_VERIFICACION_ADMON_DE_LA_CDMX_5.2.pdf` },
        { nombre: 'Ley de Publicidad Exterior de la Ciudad de México', url: `${CDMX_BASE}/LEY_DE_PUBLICIDAD_EXTERIOR_DE_LA_CDMX_5.4.pdf` },
        { nombre: 'Ley para la Reconstrucción Integral de la Ciudad de México', url: `${CDMX_BASE}/LEY_PARA_LA_RECONSTRUCCION_INTEGRAL_DE_LA_CDMX_4.1.pdf` },
        { nombre: 'Ley de Residuos Sólidos de la Ciudad de México', url: `${CDMX_BASE}/2025/2026/210126/LEY_DE_RESIDUOS_SOLIDOS_DE_LA_CDMX_4.4.pdf` },
        { nombre: 'Ley de Movilidad de la Ciudad de México', url: `${CDMX_BASE}/2025/2026/210126/LEY_DE_MOVILIDAD_DE_LA_CDMX_6.8.pdf` },
        { nombre: 'Ley para Prevenir y Eliminar la Discriminación de la Ciudad de México', url: `${CDMX_BASE}/2025/LEY_PARA_PREVENIR_Y_ELIMINAR_LA_DISCRIMINACION_DE_LA_CDMX_7.3.pdf` },
        { nombre: 'Ley de Igualdad Sustantiva entre Mujeres y Hombres en la Ciudad de México', url: `${CDMX_BASE}/2025/181225/LEY_DE_IGUALDAD_SUSTANTIVA_ENTRE_MUJERES_Y_HOMBRES_EN_LA_CDMX_3.4.pdf` },
        { nombre: 'Ley de Atención Prioritaria para las Personas con Discapacidad y en Situación de Vulnerabilidad en la Ciudad de México', url: `${CDMX_BASE}/LEY_DE_ATENCION_PRIORITARIA_PARA_LAS_PERSONAS_CON_DISCAPACIDAD_DE_LA_CDMX_2.1.pdf` },
        { nombre: 'Ley de los Derechos de las Personas Jóvenes en la Ciudad de México', url: `${CDMX_BASE}/LEY_DE_LOS_DERECHOS_DE_LAS_PERSONAS_JOVENES_EN_LA_CDMX_5.3.pdf` },
        { nombre: 'Ley de Atención Integral para el Desarrollo de las Niñas y los Niños en Primera Infancia en la Ciudad de México', url: `${CDMX_BASE}/leyes/LEY_DE_ATENCION_INTEGRAL_PARA_EL_DESARROLLO_DE_LAS_NINAS_Y_LOS_NINOS_EN_PRIMERA_INFANCIA_EN_LA_CDMX_3.1.pdf` },
        { nombre: 'Ley de los Derechos de las Personas Adultas Mayores de la Ciudad de México', url: `${CDMX_BASE}/2025/LEY_DE_LOS_DERECHOS_DE_LAS_PERSONAS_ADULTAS_MAYORES_DE_LA_CDMX_4.3.pdf` },
        { nombre: 'Ley para la Integración al Desarrollo de las Personas con Discapacidad de la Ciudad de México', url: `${CDMX_BASE}/LEY_PARA_LA_INTEGRACION_AL_DESARROLLO_DE_LAS_PERSONAS_CON_DISCAPACIDAD_DEL_DF_5.2.pdf` },
        { nombre: 'Ley de Interculturalidad, Atención a Migrantes y Movilidad Humana de la Ciudad de México', url: `${CDMX_BASE}/LEY_DE_INTERCULTURALIDAD_ATENCION_A_MIGRANTES_Y_MOV_HUM_EN_LA_CDMX_4.2.pdf` },
        { nombre: 'Ley de Asistencia y Prevención de la Violencia Familiar', url: `${CDMX_BASE}/LEY_DE_ASISTENCIA_Y_PREVENCION_DE_LA_VIOLENCIA_FAMILIAR_3.3.pdf` },
        { nombre: 'Ley de Responsabilidad Patrimonial del Distrito Federal', url: `${CDMX_BASE}/LEY_DE_RESPONSABILIDAD_PATRIMONIAL_DEL_DF_2.2.pdf` },
        { nombre: 'Ley de Extinción de Dominio para la Ciudad de México', url: `${CDMX_BASE}/LEY_DE_EXTINCION_DE_DOMINIO_PARA_LA_CDMX_3.1.pdf` },
        { nombre: 'Ley de Justicia Alternativa del Tribunal Superior de Justicia para la Ciudad de México', url: `${CDMX_BASE}/LEY_DE_JUSTICIA_ALTERNATIVA_DEL_TSJ_PARA_LA_CDMX_6.3.pdf` },
        { nombre: 'Ley de Mediación, Conciliación y Promoción de la Paz Social para la Ciudad de México', url: `${CDMX_BASE}/LEY_DE_MEDIACION_CONCILIACION_Y_PROM_DE_LA_PAZ_SOCIAL_PARA_LA_CDMX_2.3.pdf` },
        { nombre: 'Ley de Ejecución de Sanciones Penales y Reinserción Social para la Ciudad de México', url: `${CDMX_BASE}/2025/LEY_DE_EJEC_DE_SANCIONES_PENALES_Y_REINSERCION_SOCIAL_PARA_LA_CDMX_6.3.pdf` },
        { nombre: 'Ley de Víctimas para la Ciudad de México', url: `${CDMX_BASE}/LEY_DE_VICTIMAS_PARA_LA_CDMX_5.3.pdf` },
        { nombre: 'Ley de Atención a Personas en Riesgo de Vivir en la Calle y en la Calle de la CDMX', url: `${CDMX_BASE}/LEY_DE_ATENCION_A_PERSONAS_EN_RIESGO_DE_VIVIR_EN_LA_CALLE_Y_EN_LA_CALLE_DE_LA_CDMX_2.1.pdf` },
        { nombre: 'Ley de Cementerios para la Ciudad de México', url: `${CDMX_BASE}/LEY_DE_CEMENTERIOS_PARA_LA_CDMX_2.1.pdf` },
        { nombre: 'Ley de Turismo de la Ciudad de México', url: `${CDMX_BASE}/LEY_DE_TURISMO_DE_LA_CDMX_4.3.pdf` },
        { nombre: 'Ley de Fomento Cultural de la Ciudad de México', url: `${CDMX_BASE}/LEY_DE_FOMENTO_CULTURAL_DE_LA_CDMX_4.2.pdf` },
        { nombre: 'Ley de Filmaciones de la Ciudad de México', url: `${CDMX_BASE}/LEY_DE_FILMACIONES_DE_LA_CDMX_2.2.pdf` },
        { nombre: 'Ley de Economía Social y Solidaria para la Ciudad de México', url: `${CDMX_BASE}/LEY_DE_EC_SOCIAL_Y_SOL_PARA_LA_CDMX_2.1.pdf` },
        { nombre: 'Ley de Fomento Cooperativo para la Ciudad de México', url: `${CDMX_BASE}/LEY_DE_FOMENTO_COOPERATIVO_PARA_LA_CDMX_3.2.pdf` },
        { nombre: 'Ley de Desarrollo Económico de la Ciudad de México', url: `${CDMX_BASE}/2025/LEY_DE_DESARROLLO_ECONOMICO_DE_LA_CDMX_3.2.pdf` },
        { nombre: 'Ley para el Desarrollo del Distrito Federal como Ciudad Digital y del Conocimiento', url: `${CDMX_BASE}/LEY_PARA_EL_DESARROLLO_DEL_DF_COMO_CIUDAD_DIGITAL_Y_DEL_CONOCIMIENTO_2.3.pdf` },
        { nombre: 'Ley de Protección a la Salud de los No Fumadores en el Distrito Federal', url: `${CDMX_BASE}/LEY_DE_PROTECCION_A_LA_SALUD_DE_LOS_NO_FUMADORES_EN_EL_DF_2.pdf` },
        { nombre: 'Ley de Voluntad Anticipada para la Ciudad de México', url: `${CDMX_BASE}/LEY_DE_VOLUNTAD_ANTICIPADA_PARA_LA_CDMX_4.2.pdf` },
        { nombre: 'Ley de Cuidados Alternativos para Niñas, Niños y Adolescentes en la Ciudad de México', url: `${CDMX_BASE}/LEY_DE_CUIDADOS_ALTERNATIVOS_PARA_NNA_EN_LA_CDMX_3.1.pdf` },
        { nombre: 'Ley de Gestión Integral de Riesgos y Protección Civil de la Ciudad de México', url: `${CDMX_BASE}/2025/2026/210126/LEY_DE_GESTION_INTEGRAL_DE_RIESGOS_Y_PROTECCION_CIVIL_DE_LA_CDMX_5.5.pdf` },
        { nombre: 'Ley de Mitigación y Adaptación al Cambio Climático y Desarrollo Sustentable para la Ciudad de México', url: `${CDMX_BASE}/LEY_DE_MIT_Y_ADAP_AL_CAMBIO_CLIMATICO_Y_DESARROLLO_SUSTENTABLE_PARA_LA_CDMX_5.3.pdf` },
        { nombre: 'Ley de Aguas de la Ciudad de México', url: `${CDMX_BASE}/LEY_DE_AGUAS_DE_LA_CDMX_3.4.pdf` },
        { nombre: 'Ley del Derecho al Acceso, Disposición y Saneamiento del Agua de la Ciudad de México', url: `${CDMX_BASE}/LEY_DEL_DERECHO_AL_ACCESO_DISPOSICION_Y_SANEAMIENTO_DEL_AGUA_DE_LA_CDMX_2.2.pdf` },
        { nombre: 'Ley del Sistema de Alerta Sísmica de la Ciudad de México', url: `${CDMX_BASE}/leyes/LEY_DEL_SISTEMA_DE_ALERTA_SISMICA_CDMX_1.3.pdf` },
        { nombre: 'Ley de Construcciones y Servicios Urbanos para los Municipios del Estado', url: `${CDMX_BASE}/LEY_PARA_LA_ATENCION_INTEGRAL_DE_SUSTANCIAS_PSICOACTIVAS_CDMX_2.1.pdf` },
        { nombre: 'Ley de Impacto Ambiental y Riesgos de la Ciudad de México', url: `${CDMX_BASE}/LEY_DE_IMPACTO_AMBIENTAL_Y_RIESGOS_DE_LA_CDMX_2.pdf` },
        { nombre: 'Ley de Huertos Urbanos en la Ciudad de México', url: `${CDMX_BASE}/LEY_DE_HUERTOS_URBANOS_EN_LA_CDMX_2.2.pdf` },
        { nombre: 'Ley de Economía Circular de la Ciudad de México', url: `${CDMX_BASE}/leyes/LEY_DE_ECONOMIA_CIRCULAR_DE_LA_CDMX_1.2.pdf` },
        { nombre: 'Ley del Sistema de Seguridad Alimentaria y Nutricional de la Ciudad de México', url: `${CDMX_BASE}/leyes/LEY_DEL_SIS_DE_SEG_ALIM_Y_NUT_DE_LA_CDMX_2.pdf` },
        { nombre: 'Ley de Cultura Física y Deporte de la Ciudad de México', url: `${CDMX_BASE}/LEY_DE_CULTURA_FISICA_Y_DEPORTE_DE_LA_CDMX_3.4.pdf` },
        { nombre: 'Ley Orgánica de la Fiscalía General de Justicia de la Ciudad de México', url: `${CDMX_BASE}/2025/181225/LEY_ORGANICA_DE_LA_FISCALIA_GENERAL_DE_JUSTICIA_DE_LA_CDMX_7.3.pdf` },
        { nombre: 'Ley del Heroico Cuerpo de Bomberos de la Ciudad de México', url: `${CDMX_BASE}/LEY_DEL_HEROICO_CUERPO_DE_BOMBEROS_DE_LA_CDMX_3.1.pdf` },
        { nombre: 'Ley de la Comisión de Derechos Humanos de la Ciudad de México', url: `${CDMX_BASE}/2025/LEY_DE_LA_COMISION_DE_DERECHOS_HUMANOS_DE_LA_CDMX_5.5.pdf` },
        { nombre: 'Ley del Servicio Público de Carrera de la Administración Pública de la Ciudad de México', url: `${CDMX_BASE}/LEY_DEL_SERVICIO_PUBLICO_DE_CARRERA_DE_LA_AP_DE_LA_CDMX_3.2.pdf` },
        { nombre: 'Ley de Infraestructura Física Educativa de la Ciudad de México', url: `${CDMX_BASE}/LEY_DE_INFRAESTRUCTURA_FISICA_EDUCATIVA_DE_LA_CDMX_3.2.pdf` },
        { nombre: 'Ley del Centro de Conciliación Laboral de la Ciudad de México', url: `${CDMX_BASE}/leyes/LEY_DEL_CENTRO_DE_CONCILIACION_LABORAL_DE_LA_CDMX_2.1.pdf` },
        { nombre: 'Ley de Espacios Culturales Independientes de la Ciudad de México', url: `${CDMX_BASE}/leyes/LEY_DE_ESP_CULTURALES_INDEPENDIENTES_DE_LA_CDMX_2.2.pdf` },
        { nombre: 'Ley de Ciencia, Tecnología e Innovación de la Ciudad de México', url: `${CDMX_BASE}/LEY_DE_CIENCIA_TECNOLOGIA_E_INNOVACION_DE_LA_CDMX_3.2.pdf` },
        { nombre: 'Ley Constitucional de Derechos Humanos y sus Garantías de la Ciudad de México', url: `${CDMX_BASE}/LEY_CONSTITUCIONAL_DE_DERECHOS_HUMANOS_Y_SUS_GARANTIAS_DE_LA_CDMX_3.2.pdf` },
        { nombre: 'Ley de Gobierno Electrónico de la Ciudad de México', url: `${CDMX_BASE}/leyes/LEY_DE_GOBIERNO_ELECTRONICO_DE_LA_CDMX_3.2.pdf` },
        { nombre: 'Ley de Operación e Innovación Digital de la Ciudad de México', url: `${CDMX_BASE}/LEY_DE_OPERACION_E_INNOVACION_DIGITAL_DE_LA_CDMX_2.2.pdf` },
        { nombre: 'Ley Orgánica de la Administración Pública de la Ciudad de México', url: `${CDMX_BASE}/LEY_ORG_DE_LA_ADMON_PUBLICA_DE_LA_CDMX_1.pdf` },
        { nombre: 'Ley del Instituto de Estudios Constitucionales de la Ciudad de México', url: `${CDMX_BASE}/leyes/LEY_DEL_INST_DE_ESTUDIOS_CONSTITUCIONALES_DE_LA_CDMX.pdf` },
        { nombre: 'Ley Orgánica del Centro de Conciliación Laboral de la Ciudad de México', url: `${CDMX_BASE}/leyes/LEY_ORG_DEL_CENTRO_DE_CONCILIACION_LABORAL_DE_LA_CDMX_2.pdf` },
    ],
    codigos: [
        { nombre: 'Código Fiscal de la Ciudad de México', url: `${CDMX_BASE}/2025/2026/210126/CODIGO_FISCAL_DE_LA_CDMX_26.1.pdf` },
        { nombre: 'Código de Instituciones y Procedimientos Electorales de la Ciudad de México', url: `${CDMX_BASE}/codigos/CODIGO_DE_INSTITUCIONES_Y_PROC_ELECTORALES_CDMX_6.pdf` },
        { nombre: 'Código de Ética de la Administración Pública de la Ciudad de México', url: `${CDMX_BASE}/codigos/CODIGO_DE_ETICA_DE_LA_AP_DE_LA_CIUDAD_DE_MEXICO_2.1.pdf` },
        { nombre: 'Código de Responsabilidad Parlamentaria del Congreso de la Ciudad de México', url: `${CDMX_BASE}/codigos/CODIGO_DE_RESPONSABILIDAD_PARLAMENTARIA_DEL_CONGRESO_DE_LA_CIUDAD_DE_MEXICO_2.1.pdf` },
        { nombre: 'Código de Procedimientos Civiles para el Distrito Federal', url: `${CDMX_BASE}/codigos/Codigo_Procedimientos_Civiles_DF_2.2.pdf` },
        { nombre: 'Código Civil para el Distrito Federal', url: `${CDMX_BASE}/2025/CODIGOS_2025/CODIGO_CIVIL_PARA_EL_DF_15.3.pdf` },
        { nombre: 'Código Penal para el Distrito Federal', url: `${CDMX_BASE}/2025/2026/50226/CODIGO_PENAL_PARA_EL_DF_12.3.4.pdf` },
        { nombre: 'Código de Ética de los Servidores Públicos para el Distrito Federal', url: `${CDMX_BASE}/codigos/Codigo_de_etica_de_los_servidores_publicos_del_DF_3.pdf` },
    ],
    reglamentos: [
        { nombre: 'Reglamento de la Ley de Turismo de la Ciudad de México', url: `${CDMX_BASE}/reglamentos/RGTO_DE_LA_LEY_DE_TURISMO_DE_LA_CDMX_1.pdf` },
        { nombre: 'Reglamento del Registro Civil de la Ciudad de México', url: `${CDMX_BASE}/reglamentos/REGLAMENTO_DEL_REGISTRO_CIVIL_DE_LA_CDMX_1.1.pdf` },
        { nombre: 'Reglamento de la Ley de Establecimientos Mercantiles para la Ciudad de México', url: `${CDMX_BASE}/reglamentos/REGLAMENTO_DE_LA_LEY_DE_ESTABLECIMIENTOS_MERCANTILES_PARA_LA_CIUDAD_DE_MEXICO_2.pdf` },
        { nombre: 'Reglamento de la Ley de Cultura Cívica de la Ciudad de México', url: `${CDMX_BASE}/reglamentos/REGLAMENTO_DE_LA_LEY_DE_CULTURA_CIVICA_DE_LA_CDMX.pdf` },
        { nombre: 'Reglamento de la Ley del Notariado en la Ciudad de México', url: `${CDMX_BASE}/reglamentos/REGLAMENTO_DE_LA_LEY_DEL_NOTARIADO_EN_LA_CIUDAD_DE_MEXICO_1.pdf` },
        { nombre: 'Reglamento de la Ley de Publicidad Exterior de la Ciudad de México', url: `${CDMX_BASE}/reglamentos/RTO_LEY_DE_PUBLICIDAD_EXTERIOR_CDMX_2.6.pdf` },
        { nombre: 'Reglamento de la Ley de Huertos Urbanos de la Ciudad de México', url: `${CDMX_BASE}/reglamentos/rgto_de_la_ley_de_huertos_urbanos_cdmx.pdf` },
        { nombre: 'Reglamento de la Ley de Economía Circular de la Ciudad de México', url: `${CDMX_BASE}/reglamentos/RTO_ECONOMIA_CIRCULAR_CDMX.pdf` },
        { nombre: 'Reglamento de la Ley de Espacios Culturales Independientes de la Ciudad de México', url: `${CDMX_BASE}/reglamentos/RTO_LEY_ESP_CULTURALES_IND_CDMX.2.pdf` },
        { nombre: 'Reglamento de Construcciones para la Ciudad de México', url: `${CDMX_BASE}/reglamentos/REGLAMENTO_DE_CONSTRUCCIONES_PARA_LA_CDMX_4.4.pdf` },
        { nombre: 'Reglamento de la Ley Ambiental del Distrito Federal', url: `${CDMX_BASE}/reglamentos/RGTO_DE_LA_LEY_AMBIENTAL_DEL_DF_2.2.pdf` },
        { nombre: 'Reglamento de la Ley de Residuos Sólidos para el Distrito Federal', url: `${CDMX_BASE}/reglamentos/RGTO_LEY_DE_RESIDUOS_SOLIDOS_2.1.pdf` },
        { nombre: 'Reglamento de Tránsito de la Ciudad de México', url: `${CDMX_BASE}/reglamentos/REGLAMENTO_DE_TRANSITO_DE_LA_CDMX_4.3.pdf` },
        { nombre: 'Reglamento de la Ley de Movilidad de la Ciudad de México', url: `${CDMX_BASE}/reglamentos/REGLAMENTO_DE_LA_LEY_DE_MOVILIDAD_DE_LA_CDMX.pdf` },
        { nombre: 'Reglamento de la Ley de Salud de la Ciudad de México', url: `${CDMX_BASE}/reglamentos/RGTO_DE_LA_LEY_DE_SALUD_DEL_DF_3.pdf` },
        { nombre: 'Reglamento de la Ley de Protección de Datos Personales en Posesión de Sujetos Obligados de la CDMX', url: `${CDMX_BASE}/reglamentos/RGTO_LEY_PROTECCION_DATOS_PERSONALES_CDMX.pdf` },
        { nombre: 'Reglamento de la Ley de Desarrollo Urbano del Distrito Federal', url: `${CDMX_BASE}/reglamentos/RGTO_DE_LA_LEY_DE_DESARROLLO_URBANO_DEL_DF_2.3.pdf` },
        { nombre: 'Reglamento de Cementerios del Distrito Federal', url: `${CDMX_BASE}/reglamentos/RGTO_DE_CEMENTERIOS_DEL_DF_1.1.pdf` },
        { nombre: 'Reglamento de la Ley de Obras Públicas de la Ciudad de México', url: `${CDMX_BASE}/reglamentos/RGTO_DE_LA_LEY_DE_OBRAS_PUBLICAS_DE_LA_CDMX_2.pdf` },
        { nombre: 'Reglamento de la Ley de Adquisiciones para el Distrito Federal', url: `${CDMX_BASE}/reglamentos/RGTO_LEY_DE_ADQUISICIONES_PARA_EL_DF_2.1.pdf` },
        { nombre: 'Reglamento de la Ley de Protección y Bienestar de los Animales de la CDMX', url: `${CDMX_BASE}/reglamentos/RGTO_DE_LA_LEY_DE_PROTECCION_A_LOS_ANIMALES_DEL_DF_1.1.pdf` },
        { nombre: 'Reglamento de la Ley de Gestión Integral de Riesgos y Protección Civil de la CDMX', url: `${CDMX_BASE}/reglamentos/RGTO_DE_LA_LEY_DE_GESTION_INTEGRAL_DE_RIESGOS_Y_PROTECCION_CIVIL_1.pdf` },
        { nombre: 'Reglamento de la Ley de Archivos de la Ciudad de México', url: `${CDMX_BASE}/reglamentos/REGLAMENTO_DE_LA_LEY_DE_ARCHIVOS_DE_LA_CDMX.pdf` },
        { nombre: 'Reglamento de la Ley de Vivienda para la Ciudad de México', url: `${CDMX_BASE}/reglamentos/RGTO_DE_LA_LEY_DE_VIVIENDA_DE_LA_CDMX.pdf` },
        { nombre: 'Reglamento de la Ley de Propiedad en Condominio de Inmuebles del Distrito Federal', url: `${CDMX_BASE}/reglamentos/RGTO_DE_LA_LEY_DE_PROPIEDAD_EN_CONDOMINIO_DE_INMUEBLES_DEL_DF_1.2.pdf` },
    ],
    otros: [],
};

// ─── All 32 States ────────────────────────────────────────────
export const ESTADOS: Estado[] = [
    { slug: 'aguascalientes', nombre: 'Aguascalientes', nombreCorto: 'Aguascalientes', abreviatura: 'AGS', region: 'centro', leyesCount: 0, leyes: LEYES_PLACEHOLDER },
    { slug: 'baja-california', nombre: 'Baja California', nombreCorto: 'Baja California', abreviatura: 'BC', region: 'norte', leyesCount: 0, leyes: LEYES_PLACEHOLDER },
    { slug: 'baja-california-sur', nombre: 'Baja California Sur', nombreCorto: 'B.C. Sur', abreviatura: 'BCS', region: 'norte', leyesCount: 0, leyes: LEYES_PLACEHOLDER },
    { slug: 'campeche', nombre: 'Campeche', nombreCorto: 'Campeche', abreviatura: 'CAMP', region: 'sur', leyesCount: 0, leyes: LEYES_PLACEHOLDER },
    { slug: 'chiapas', nombre: 'Chiapas', nombreCorto: 'Chiapas', abreviatura: 'CHIS', region: 'sur', leyesCount: 0, leyes: LEYES_PLACEHOLDER },
    { slug: 'chihuahua', nombre: 'Chihuahua', nombreCorto: 'Chihuahua', abreviatura: 'CHIH', region: 'norte', leyesCount: 0, leyes: LEYES_PLACEHOLDER },
    { slug: 'cdmx', nombre: 'Ciudad de México', nombreCorto: 'CDMX', abreviatura: 'CDMX', region: 'centro', leyesCount: 139, ultimaActualizacion: '2026-02-15', leyes: CDMX_LEYES },
    { slug: 'coahuila', nombre: 'Coahuila', nombreCorto: 'Coahuila', abreviatura: 'COAH', region: 'norte', leyesCount: 0, leyes: LEYES_PLACEHOLDER },
    { slug: 'colima', nombre: 'Colima', nombreCorto: 'Colima', abreviatura: 'COL', region: 'occidente', leyesCount: 0, leyes: LEYES_PLACEHOLDER },
    { slug: 'durango', nombre: 'Durango', nombreCorto: 'Durango', abreviatura: 'DGO', region: 'norte', leyesCount: 0, leyes: LEYES_PLACEHOLDER },
    { slug: 'guanajuato', nombre: 'Guanajuato', nombreCorto: 'Guanajuato', abreviatura: 'GTO', region: 'centro', leyesCount: 0, leyes: LEYES_PLACEHOLDER },
    { slug: 'guerrero', nombre: 'Guerrero', nombreCorto: 'Guerrero', abreviatura: 'GRO', region: 'sur', leyesCount: 0, leyes: LEYES_PLACEHOLDER },
    { slug: 'hidalgo', nombre: 'Hidalgo', nombreCorto: 'Hidalgo', abreviatura: 'HGO', region: 'centro', leyesCount: 0, leyes: LEYES_PLACEHOLDER },
    { slug: 'jalisco', nombre: 'Jalisco', nombreCorto: 'Jalisco', abreviatura: 'JAL', region: 'occidente', leyesCount: 0, leyes: LEYES_PLACEHOLDER },
    { slug: 'estado-de-mexico', nombre: 'Estado de México', nombreCorto: 'Edo. México', abreviatura: 'EDOMEX', region: 'centro', leyesCount: 0, leyes: LEYES_PLACEHOLDER },
    { slug: 'michoacan', nombre: 'Michoacán', nombreCorto: 'Michoacán', abreviatura: 'MICH', region: 'occidente', leyesCount: 0, leyes: LEYES_PLACEHOLDER },
    { slug: 'morelos', nombre: 'Morelos', nombreCorto: 'Morelos', abreviatura: 'MOR', region: 'centro', leyesCount: 0, leyes: LEYES_PLACEHOLDER },
    { slug: 'nayarit', nombre: 'Nayarit', nombreCorto: 'Nayarit', abreviatura: 'NAY', region: 'occidente', leyesCount: 0, leyes: LEYES_PLACEHOLDER },
    { slug: 'nuevo-leon', nombre: 'Nuevo León', nombreCorto: 'Nuevo León', abreviatura: 'NL', region: 'norte', leyesCount: 0, leyes: LEYES_PLACEHOLDER },
    { slug: 'oaxaca', nombre: 'Oaxaca', nombreCorto: 'Oaxaca', abreviatura: 'OAX', region: 'sur', leyesCount: 0, leyes: LEYES_PLACEHOLDER },
    { slug: 'puebla', nombre: 'Puebla', nombreCorto: 'Puebla', abreviatura: 'PUE', region: 'centro', leyesCount: 0, leyes: LEYES_PLACEHOLDER },
    { slug: 'queretaro', nombre: 'Querétaro', nombreCorto: 'Querétaro', abreviatura: 'QRO', region: 'centro', leyesCount: 138, ultimaActualizacion: '2026-02-14', leyes: QUERETARO_LEYES },
    { slug: 'quintana-roo', nombre: 'Quintana Roo', nombreCorto: 'Quintana Roo', abreviatura: 'QROO', region: 'sur', leyesCount: 0, leyes: LEYES_PLACEHOLDER },
    { slug: 'san-luis-potosi', nombre: 'San Luis Potosí', nombreCorto: 'San Luis Potosí', abreviatura: 'SLP', region: 'centro', leyesCount: 0, leyes: LEYES_PLACEHOLDER },
    { slug: 'sinaloa', nombre: 'Sinaloa', nombreCorto: 'Sinaloa', abreviatura: 'SIN', region: 'norte', leyesCount: 0, leyes: LEYES_PLACEHOLDER },
    { slug: 'sonora', nombre: 'Sonora', nombreCorto: 'Sonora', abreviatura: 'SON', region: 'norte', leyesCount: 0, leyes: LEYES_PLACEHOLDER },
    { slug: 'tabasco', nombre: 'Tabasco', nombreCorto: 'Tabasco', abreviatura: 'TAB', region: 'sur', leyesCount: 0, leyes: LEYES_PLACEHOLDER },
    { slug: 'tamaulipas', nombre: 'Tamaulipas', nombreCorto: 'Tamaulipas', abreviatura: 'TAMPS', region: 'norte', leyesCount: 0, leyes: LEYES_PLACEHOLDER },
    { slug: 'tlaxcala', nombre: 'Tlaxcala', nombreCorto: 'Tlaxcala', abreviatura: 'TLAX', region: 'centro', leyesCount: 0, leyes: LEYES_PLACEHOLDER },
    { slug: 'veracruz', nombre: 'Veracruz', nombreCorto: 'Veracruz', abreviatura: 'VER', region: 'oriente', leyesCount: 0, leyes: LEYES_PLACEHOLDER },
    { slug: 'yucatan', nombre: 'Yucatán', nombreCorto: 'Yucatán', abreviatura: 'YUC', region: 'sur', leyesCount: 0, leyes: LEYES_PLACEHOLDER },
    { slug: 'zacatecas', nombre: 'Zacatecas', nombreCorto: 'Zacatecas', abreviatura: 'ZAC', region: 'norte', leyesCount: 0, leyes: LEYES_PLACEHOLDER },
];

// ─── Helpers ──────────────────────────────────────────────────
export function getEstadoBySlug(slug: string): Estado | undefined {
    return ESTADOS.find(e => e.slug === slug);
}

export function getTotalLeyes(leyes: CategoriaLeyes): number {
    return leyes.constitucion.length + leyes.leyes.length + leyes.codigos.length + leyes.reglamentos.length + leyes.otros.length;
}

// ─── Category metadata for UI rendering ───────────────────────
export const CATEGORIA_META: Record<keyof CategoriaLeyes, { label: string; icon: string; color: string }> = {
    constitucion: { label: 'Constitución Local', icon: '🏛️', color: 'text-amber-600' },
    leyes: { label: 'Leyes', icon: '📜', color: 'text-blue-600' },
    codigos: { label: 'Códigos', icon: '📕', color: 'text-red-600' },
    reglamentos: { label: 'Reglamentos', icon: '📋', color: 'text-green-600' },
    otros: { label: 'Leyes Orgánicas y Otros', icon: '📎', color: 'text-gray-600' },
};

// ─── Region colors for state cards ────────────────────────────
export const REGION_COLORS: Record<string, { bg: string; text: string; border: string }> = {
    norte: { bg: 'bg-orange-50', text: 'text-orange-700', border: 'border-orange-200' },
    centro: { bg: 'bg-amber-50', text: 'text-amber-700', border: 'border-amber-200' },
    sur: { bg: 'bg-green-50', text: 'text-green-700', border: 'border-green-200' },
    occidente: { bg: 'bg-blue-50', text: 'text-blue-700', border: 'border-blue-200' },
    oriente: { bg: 'bg-emerald-50', text: 'text-emerald-700', border: 'border-emerald-200' },
};
